#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config window_topmost               on
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# rules
# https://github.com/koekeishiya/yabai/wiki/Commands#automation-with-rules-and-signals
yabai -m rule --add app="^Messages\$"        manage=off
yabai -m rule --add app="^iTerm2\$"          opacity=0.95

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Fira Code:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

update_battery_loop() {
    while true; do
        # Get the current battery percentage.
        battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

        if [ "$battery" -gt 84 ]; then
            yabai -m config status_bar_power_icon_strip  
        elif [ "$battery" -gt 60 ]; then
            yabai -m config status_bar_power_icon_strip  
        elif [ "$battery" -gt 39 ]; then
            yabai -m config status_bar_power_icon_strip  
        elif [ "$battery" -gt 14 ]; then
            yabai -m config status_bar_power_icon_strip  
        else
            yabai -m config status_bar_power_icon_strip  
        fi

        sleep 300 # 5 minutes
    done
}

# run the function async
update_battery_loop &

echo "$(date "+%Y-%m-%d %H:%M:%S") yabai configuration loaded.."
